name: Deploy Laravel via SFTP

on:
  push:
    branches: [ main ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate deployments

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4' 
          extensions: mbstring, xml, bcmath, curl

      - name: Install Dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Sync Files via SFTP
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "ftp"
          remote-host: ${{ secrets.FTP_HOST }}
          remote-user: ${{ secrets.FTP_USERNAME }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          remote-path: ${{ secrets.FTP_REMOTE_PATH }}
          sync: "full" 
